spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update #create,update,none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      database: 0
    session:
      store-type: redis
      timeout: 1800
server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
    session:
      cookie:
        name: JSESSIONID

spotify:
  clientId: "345d71b717834eb7a4c0136d98112fe0"
  clientSecret: "9b65b554fe7f4d47a6cddff37b9662f3"